app1/urls.py
from django.urls import path
from .views import HomePageView, DetailPageView,CreatePageView,UpdatePageView
from .views import DeletePageView

urlpatterns = [
    path('', HomePageView.as_view(), name = "home"),
    path('detail/<int:pk>', DetailPageView.as_view(), name = "detail"),
    path("create",CreatePageView.as_view(),name="create"),
    path("detail/<int:pk>/update",UpdatePageView.as_view(),name="update"),
    path("detail/<int:pk>/delete",DeletePageView.as_view(),name="delete"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app', include('app1.urls')),
    path('',include('registro.urls'))
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

registro/urls.py
from django.urls import path,include
from .views import SignupView,FirstPage,LogoutPageView

urlpatterns=[

    path("account/",include('django.contrib.auth.urls')),
    path("signup",SignupView.as_view(),name="signup"),
    path("",FirstPage.as_view(),name="first_page"),
    path("logout1",LogoutPageView.as_view(),name="logout1"),

]

app1/models.py
from django.db import models

# Create your models here.

class Publicaciones(models.Model):
    titulo = models.CharField(max_length = 50)
    descripcion = models.TextField()
    author = models.ForeignKey("auth.User", on_delete = models.CASCADE, blank = True,null=True)
    image= models.ImageField(upload_to="media", blank=True, null=True)

    def __str__(self):
        return self.titulo

registro/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from django.views.generic.edit import UpdateView, CreateView
from django.views.generic.edit import DeleteView
from .models import Publicaciones
from django.urls import reverse_lazy

# Create your views here.

class HomePageView(ListView):
    template_name = "home.html"
    model = Publicaciones


class DetailPageView(DetailView):
    template_name = "post_detail.html"
    model = Publicaciones

class UpdatePageView(UpdateView):

    template_name="post_update.html"
    model= Publicaciones
    fields=["titulo","descripcion","image"]
    success_url=reverse_lazy("home")
    
class CreatePageView(CreateView):

    template_name= "post_create.html"
    model=Publicaciones
    fields=["titulo","descripcion","image"]
    success_url=reverse_lazy("home")



    

class DeletePageView(DeleteView):

    template_name="post_delete.html"
    model=Publicaciones
    success_url=reverse_lazy("home")

registro/views.py
from django.shortcuts import render

from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView

# Create your views here.


class SignupView(CreateView):

    form_class = UserCreationForm
    template_name="registration/signup.html"
    success_url=reverse_lazy("login")

class FirstPage(TemplateView):

    template_name="registration/first_page.html"

class LogoutPageView(TemplateView):

    template_name="registration/logout.html"

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'home' %}"> <input type="submit" value="Go back"></a>

    {% block content %}

    
    {% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

    {% for publicacion in publicaciones_list %}

        <p><a href="{% url 'detail' publicacion.pk %}"> {{ publicacion.titulo }}</a>

    {% endfor %}</p>

    <p><a href="{% url 'create' %}"><input type="submit" value="Crear Post"></a></p>
    
{% endblock %}  

templates/post_create.html
{% extends 'base.html' %}


{% block content %}


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="Crear">

</form>


{% endblock %}

templates/post_delete.html
{% extends 'base.html' %} 


{% block content %}

<p>Seguro que quieres borrar esto</p>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Borrar">
</form>

{% endblock %}

templates/post_detail.html
{% extends 'base.html' %}


{% block content %}


    <h2>{{object.titulo}}</h2>
    <p>{{object.descripcion}}</p>

    {% if object.image %}
    <img src="{{ object.image.url }}" >
    {% endif %}

    <a href="{% url 'update' object.pk %}">Actualizar</a>
    <a href="{% url 'delete' object.pk %}">Borrar</a>


{% endblock %}

templates/post_update.html
{% extends "base.html" %}



{% block content %}

 <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="Actualizar">
    
 </form>

{% endblock %}